#' Parse and Process DrugBank Interaction Data
#'
#' Extracts and processes drug-target interaction data from a DrugBank XML file.
#' The function calls a Python parser script, filters for complete records with
#' PubChem CID, PubMed IDs, and UniProt IDs, expands multi-valued PubMed ID fields,
#' and joins with UniProt mapping data.  Additionally, the parent-child relationships
#' among the drugs is inspected and any children are removed if the parent is in the 
#' dataset already.  Note: The `parse_drugbank.py` script creates temporary CSV files
#' ('parsed_drugbank.csv' and 'parsed_drugbank_drug_info.csv') in the same directory as
#' the input XML file.
#'
#' @param drugbank.xml Path to the DrugBank XML file to be parsed.
#' @param cid.par.file Path of PubChem CID -> parental PubChem CID mapping file from PubChem 
#' @param unip.map UniProt mapping data with at least a column
#'   named 'V3' containing UniProt IDs. Columns 'V1' and 'V2' will be removed from
#'   the final output.
#'
#' @return A tibble containing processed drug-bank interactions.
#'
get.drugbank.interactions <- function(drugbank.xml, cid.par.file, unip.map) {
    out.file <- file.path(dirname(drugbank.xml), "parsed_drugbank.csv")
    
    system2("python", args = c("parse_drugbank.py", "-i", drugbank.xml, "-o", out.file))
    
    db.inters <- readr::read_delim(out.file)
    
    complete.inters <- db.inters %>%
        filter(is.na(pubchem_cid) == F &
                   is.na(pubmed_ids) == F &
                   is.na(uniprot_id) == F)
    
    cmpl.inters.pmid <- separate_longer_delim(
        complete.inters,
        cols = pubmed_ids,
        delim = "|"
    )
    
    # limit drugbank to the parent compound if available
    
    cid.par <- readr::read_delim(cid.par.file) %>%
        rename(pubchem_cid = `1`, parent_cid = `2`)
    
    drugbank.par <- left_join(
        unique(select(cmpl.inters.pmid, pubchem_cid)),
        cid.par,
        by="pubchem_cid")
    
    # set the NAs to children
    
    drugbank.par <- mutate(drugbank.par, parent_cid = ifelse(is.na(parent_cid), pubchem_cid, parent_cid))
    
    fixed.drugbank.par <- lapply(group_split(drugbank.par, .by=parent_cid), function(x){
        
        new.x <- x[]
        
        new.x <- mutate(new.x, new_pubchem_cid=pubchem_cid)
        
        # if only 1, set to the parent
        
        if (nrow(new.x) == 1){
            new.x$new_pubchem_cid <- new.x$parent_cid
            
        }else if (nrow(new.x) > 1 & sum(new.x$pubchem_cid == new.x$parent_cid) > 0){
            
            # if > 1 and the parent is already in the dataset, limit to it only parent
            
            new.x <- filter(new.x, pubchem_cid == parent_cid)
            
            if (nrow(new.x) != 1){
                stop("ERROR: Expecting only a single element left")
            }
          
        }
        
        # otherwise leave at the children
        
        new.x
        
    }) %>% bind_rows()
    
    cmpl.inters.par <- inner_join(
        select(fixed.drugbank.par, pubchem_cid, new_pubchem_cid),
        cmpl.inters.pmid,
        by="pubchem_cid"
    )
    
    cmpl.inters.par$pubchem_cid <- NULL
    
    cmpl.inters.par <- 
        cmpl.inters.par %>% rename(pubchem_cid = new_pubchem_cid)
    
    #only keep valid uniprot ids
    
    cmpl.inters.unip <- inner_join(
        cmpl.inters.par,
        unip.map,
        by = c(uniprot_id = "V3")
    )
    
    cmpl.inters.unip <- rename(
        cmpl.inters.unip,
        pubmed_id = "pubmed_ids"
    )
    
    cmpl.inters.unip <- select(
        cmpl.inters.unip,
        -V1, -V2
    )
    
    cmpl.inters.unip
}

#' Add additional annotation to the DrugBank DTI tibble
#'
#' In order to make drugbank comparable to the information in Targetome, add in
#' InCHI, MeSH, ATC and drug annotation from ChEMBL for the drugs as well as drug synoyms. This code was directly
#' adapted from targetome.R : `add.inchi` and `add.chembl.annots`.
#'
#' @param drugbank DrugBank DTI `tibble` as generated by `get.drugbank.interactions`.
#' @param inchi.file Path to the PubChem “CID–InChIKey” mapping file
#'   (e.g. \code{"CID-InChI-Key.gz"}) from the PubChem FTP site
#'   (\url{https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/Extras/}).
#' @param chembl.file  Path to the ChEMBL SQLite database file (e.g., downloaded from
#'   \url{https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_36_sqlite.tar.gz}).
#' @param pharm.mesh
#'   A \code{data.table} (or tibble) produced by \code{\link{combine.mesh.pubchem}},
#'   summarizing PubChem CIDs into MeSH terms and MeSH pharmacological-action classes.
#' @param pubchem.atc.file
#'   A CSV file derived from the WHO ATC classification system applied to
#'   PubChem CIDs (e.g. mapping each CID to ATC codes).
#' @param pubchem.syn.file
#'   Path to the PubChem synonym file (e.g. \code{"CID-Synonym-filtered.gz"})
#'   from the PubChem Compound/Extras FTP directory. This file provides
#'   synonyms for each CID and is used to annotate drug names and alternate names.
#'
#' @return A list of data.tables containing annotated DrugBank interactions, drugs and synonyms.
#'
add.inchi.chembl.drugbank <- function(drugbank, inchi.file, chembl.file, pharm.mesh, pubchem.atc.file, pubchem.syn.file){
    
    # add inchi
    
    if (dir.exists("tmp") == F) {
        dir.create("tmp")
    }
    
    drugbank.drugs <- unique(as.data.table(drugbank)[,.(pubchem_cid, drug_name)])
    
    cid2inchi <- fread(inchi.file, tmpdir = "tmp")
    
    drugbank.drugs <- merge(cid2inchi[, .(pubchem_cid = V1, inchi = V2, inchi_key = V3)], drugbank.drugs, by = "pubchem_cid", all.x = F, all.y = T)
    
    # add drugbank annotations
    
    con <- dbConnect(SQLite(), chembl.file)
    
    drug.dict <- data.table(dbGetQuery(con, "select * from molecule_dictionary join compound_structures using (MOLREGNO);"))
    
    dbDisconnect(con)
    
    # note parsed from https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/schema_documentation.html
    
    phase.dt <- data.table(
        max_phase = c(NA_real_, -1, .5, 1, 2, 3, 4),
        clinical_phase = c(
            "preclinical compounds with bioactivity data",
            "Clinical Phase unknown for drug or clinical candidate drug",
            "Early Phase 1 Clinical Trials",
            "Phase 1 Clinical Trials",
            "Phase 2 Clinical Trials",
            "Phase 3 Clinical Trials",
            "Approved"
        )
    )
    
    drug.dict <- merge(drug.dict, phase.dt, by = "max_phase")
    
    drugbank.drugs <- merge(drug.dict[, .(inchi_key = standard_inchi_key, pref_name, clinical_phase, chembl_id, therapeutic_flag, molecule_type, withdrawn_flag, chemical_probe, natural_product)], 
                        drugbank.drugs, by = "inchi_key", all.x = F, all.y = T)
    
    #remove those without inchi_keys
    
    drugbank.drugs <- drugbank.drugs[is.na(inchi_key) == F]
    
    #merge in mesh/pharm-mesh
    
    drugbank.drugs <- merge(drugbank.drugs, pharm.mesh, by.x="pubchem_cid", by.y="CID", all.x=T, all.y=F)
    
    #merge in atc
    
    atc <- fread(pubchem.atc.file)
    
    drugbank.drugs <- merge(drugbank.drugs, atc[, .(pubchem_cid = cid, atc = annotation)], all.x = T, all.y = F)
    
    #add synonyms
    
    syns <- fread(pubchem.syn.file, quote = "")
    
    use.syns <- merge(drugbank.drugs[,.(pubchem_cid, inchi_key)], syns[,.(pubchem_cid=V1, synonyms=V2)], by="pubchem_cid")
    
    pref.tab <- drugbank.drugs[is.na(pref_name) == F,.(pubchem_cid, inchi_key, synonyms=pref_name)]
    
    name.tab <- merge(unique(as.data.table(drugbank)[,.(pubchem_cid, synonyms=drug_name)]), drugbank.drugs[,.(pubchem_cid, inchi_key)], by="pubchem_cid")
    
    all.syns <- rbind(
        use.syns,
        pref.tab[,names(use.syns),with=F],
        name.tab[,names(use.syns),with=F]
    )
    
    all.syns[,lower_name := sapply(synonyms, function(x) tryCatch(tolower(x), error = function(x) NA_character_))]
    
    uniq.syns <- unique(all.syns[is.na(synonyms) == F])
    
    list(drugs=drugbank.drugs, syns=uniq.syns, targets=drugbank)
}

