#' Parse and Map PubChem Bioassay Data to UniProt Identifiers
#'
#' This function reads, filters, and merges human bioactivity data from the
#' PubChem BioAssay dataset (`bioactivities.tsv.gz`) with a UniProt mapping
#' table. It retains only human protein targets that can be mapped to UniProt
#' accessions and have associated PubMed references, producing a cleaned and
#' deduplicated dataset suitable for downstream target–compound analysis.
#'
#' @param bioassay.file Character string giving the path to the PubChem
#' bioactivity dataset file, typically `"bioactivities.tsv.gz"`, obtained from
#' [PubChem BioAssay Extras](https://ftp.ncbi.nlm.nih.gov/pubchem/Bioassay/Extras/).
#' This file should be a tab-delimited file containing bioactivity data,
#' including chemical compound identifiers, target protein accessions,
#' activity measures, and PubMed IDs.
#'
#' @param unip.map A `data.table` produced by [form.uniprot.map()],
#' representing the mapping between UniProt accession IDs and other database
#' identifiers (e.g., Ensembl, GeneID). It must contain at least columns `V1`
#' (UniProt ID) and `V3` (mapped identifier, such as a protein accession).
#'
#' @return
#' A `data.table` containing deduplicated PubChem bioassay records with mapped
#' UniProt IDs. The output includes all relevant PubChem assay fields plus an
#' additional `uniprot_id` column.
#'
parse.bioassay <- function(bioassay.file, unip.map) {
  pubchem <- fread(bioassay.file, sep = "\t")

  # Require human protein targets

  pubchem.w.prot <- pubchem[`Protein Accession` != ""]

  pubchem.mapped <- merge(pubchem.w.prot, unip.map[, .(`Protein Accession` = V3, uniprot_id = V1)], by = "Protein Accession", all.x = T, allow.cartesian = T)

  pubchem.mapped <- pubchem.mapped[is.na(uniprot_id) == F]

  # Require a pubmed ID

  targetome <- pubchem.mapped[is.na(PMID) == F]

  # remove duplicates

  targetome[, assay_key := paste(CID, uniprot_id, as.character(PMID), `Activity Name`, `Activity Qualifier`, as.character(round(`Activity Value`, digits = 7)))]

  targetome <- targetome[!duplicated(assay_key)]

  targetome[, assay_key := NULL]

  targetome
}

#' Remove Bioassay Entries with Missing Compound or Activity Data
#'
#' This function filters a PubChem bioassay dataset (such as the
#' output of [parse.bioassay()]) to remove records with missing
#' compound identifiers (`CID`) or activity values (`Activity Value`).
#' It ensures that only complete bioactivity measurements are retained
#' for downstream analysis.
#'
#' @param targetome A `data.table` of PubChem bioassay records,
#' typically generated by [parse.bioassay()]. The table must contain
#' at least the columns `CID` and `Activity Value`.
#'
#' @return
#' A filtered `data.table` containing only bioassay records with valid
#' compound identifiers and activity measurements.
#'
#'
remove.bioassay.nas <- function(targetome) {
  targetome <- targetome[is.na(`Activity Value`) == F & is.na(CID) == F]

  targetome
}

#' Combine PubChem–MeSH and MeSH–Pharmacological Action mappings to annotate CIDs
#'
#' Build a mapping between PubChem compound identifiers (CIDs), MeSH terms,
#' and MeSH pharmacological action classes (pharm_MeSH) by combining two
#' flat-file mappings from the National Center for Biotechnology Information (NCBI) /
#' PubChem FTP site:
#' (1) the “CID–MeSH” file, linking CIDs to MeSH terms; and
#' (2) the “MeSH–Pharm” file, linking MeSH terms to pharmacological action categories.
#' The result is a summary table with one row per CID and two pipe-delimited annotation columns:
#' all MeSH terms associated with the CID and all MeSH pharmacological action classes associated via those MeSH terms.
#'
#' @param cid.mesh.file
#'   Path to the PubChem CID–MeSH mapping file (e.g.
#'   \code{"CID-MeSH"} or \code{"CID-MeSH.gz"}) from the PubChem FTP site.
#'   This file is read and converted to a
#'   tibble, and processed by splitting tab-delimited columns. It is expected
#'   to contain lines mapping CID → MeSH term(s).
#'
#' @param mesh.pharm.file
#'   Path to the PubChem MeSH–PharmacologicalAction mapping file (e.g.
#'   \code{"MeSH-Pharm"} or \code{"MeSH-Pharm.gz"}) from the PubChem FTP site.
#'   Also read and processed into a tibble.
#'   This file is expected to contain lines mapping a MeSH term to one or more
#'   “pharm_Mesh” (pharmacological action) annotation(s).
#'
#' @return
#' A \code{data.table} (or tibble) summarising, for each PubChem CID:
#' \itemize{
#'   \item \code{CID}: Numeric PubChem Compound ID.
#'   \item \code{mesh}: A single string containing one or more MeSH terms
#'         associated with the compound (pipe-delimited, e.g. “TermA|TermB”).
#'   \item \code{pharm_mesh}: A single string containing one or more
#'         MeSH pharmacological action classes associated through the MeSH
#'         terms (pipe-delimited, e.g. “ActionA|ActionB”).
#' }
combine.mesh.pubchem <- function(cid.mesh.file, mesh.pharm.file) {
  cids.to.mesh <- readr::read_lines(cid.mesh.file) %>%
    as_tibble() %>%
    mutate(CID = as.numeric(sapply(strsplit(value, "\t"), "[[", 1))) %>%
    separate_longer_delim(cols = value, delim = "\t") %>%
    filter(value != CID) %>%
    rename(mesh = value)

  mesh.to.pharm <- readr::read_lines(mesh.pharm.file) %>%
    as_tibble() %>%
    mutate(mesh = sapply(strsplit(value, "\t"), "[[", 1)) %>%
    separate_longer_delim(cols = value, delim = "\t") %>%
    filter(value != mesh) %>%
    rename(pharm_mesh = value)

  cid.cats <- left_join(cids.to.mesh, mesh.to.pharm, by = "mesh", relationship = "many-to-many")

  cid.sum <- group_by(cid.cats, CID) %>% summarize(mesh = paste(unique(mesh), collapse = "|"), pharm_mesh = paste(unique(pharm_mesh), collapse = "|"))

  cid.sum
}
